# Generated by Django 4.1.7 on 2023-03-31 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('supplier_inn', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ИНН компании')),
                ('supplier_kpp', models.PositiveBigIntegerField(unique=True, verbose_name='КПП компании')),
                ('okved', models.CharField(max_length=100, verbose_name='Номера ОКВЭД компании')),
                ('status', models.CharField(choices=[('A', 'active'), ('B', 'blocked')], max_length=15, verbose_name='Статус компании(Активная или Заблокирована)')),
                ('count_managers', models.PositiveIntegerField(verbose_name='Кол - во контактный лиц компании')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Номер закупки')),
                ('purchase_name', models.CharField(max_length=100, verbose_name='Название закупки')),
                ('lot_name', models.CharField(max_length=100, verbose_name='Название лота')),
                ('price', models.PositiveIntegerField(verbose_name='Начальная максимальная цена закупки, предложенная заказчиком')),
                ('delivery_region', models.CharField(max_length=100, verbose_name='Регион доставки товара')),
                ('publish_date', models.DateField(verbose_name='Дата публикации закупки')),
                ('contract_category', models.CharField(max_length=100, verbose_name=' Категория контракта(КС или Потребность)')),
                ('customer_inn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.companies', verbose_name='ИНН заказчика')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField()),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.purchases', verbose_name='Номер закупки')),
                ('supplier_inn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.companies', verbose_name='ИНН поставщика (участника)')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reg_number', models.CharField(max_length=30, verbose_name='Номер регистрации контракта')),
                ('price', models.PositiveIntegerField(verbose_name='Цена заключенного контракта')),
                ('contract_conclusion_date', models.DateField(verbose_name='Дата заключения контракта')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.purchases', verbose_name='Номер закупки')),
            ],
        ),
    ]
