# Generated by Django 4.1.7 on 2023-04-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='contract_category',
            field=models.BooleanField(verbose_name=' Категория контракта(КС или Потребность)'),
        ),
    ]
