# Generated by Django 4.1.7 on 2023-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_purchases_purchase_name_end_purchases_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='okved',
            field=models.CharField(max_length=200, verbose_name='Номера ОКВЭД компании'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='delivery_region',
            field=models.CharField(max_length=200, verbose_name='Регион доставки товара'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='lot_name',
            field=models.CharField(max_length=200, verbose_name='Название лота'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_name',
            field=models.CharField(max_length=200, verbose_name='Название закупки'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_name_end',
            field=models.CharField(default='', max_length=200),
        ),
    ]
