# Generated by Django 4.1.7 on 2023-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_companies_name_alter_companies_okved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='supplier_kpp',
        ),
        migrations.AlterField(
            model_name='companies',
            name='okved',
            field=models.CharField(default='', max_length=200, verbose_name='Номера ОКВЭД компании'),
        ),
    ]
