# Generated by Django 4.1.7 on 2023-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_purchases_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='purchase_name_end',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='vector',
            field=models.BinaryField(default=b'', null=True),
        ),
    ]
