# Generated by Django 4.1.7 on 2023-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_purchases_purchase_name_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='purchase_name_end',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='vector',
        ),
        migrations.AddField(
            model_name='purchases',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='customer_inn',
            field=models.PositiveBigIntegerField(verbose_name='ИНН компании'),
        ),
    ]
