# Generated by Django 4.1.7 on 2023-04-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_purchases_purchase_name_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='analysis.purchases', verbose_name='Номер закупки'),
        ),
    ]
