# Generated by Django 4.1.7 on 2023-04-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_participants_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='is_winner',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Начальная максимальная цена закупки, предложенная зака=зчиком'),
        ),
    ]
