# Generated by Django 4.1.7 on 2023-04-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_participants_is_winner_alter_purchases_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='cluster',
            field=models.IntegerField(default=0, verbose_name='кластер'),
        ),
    ]
