# Generated by Django 4.1.7 on 2023-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_purchases_contract_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='contract_category',
            field=models.CharField(max_length=10, verbose_name=' Категория контракта(КС или Потребность)'),
        ),
    ]
